import React , {FC,ReactNode} from 'react';
import '../styles/globals.css';
import Header from '../component/home/header'
import Footer from '../component/home/footer';
import { MyContextProvider } from './context/theme';
import Totop from '../component/totop';

export const metadata = {
  title: 'Create Next App ',
  description: 'Generated by create next app',
}


  const RootLayout:FC<{ children:ReactNode }> = ({ children }) => {
  return (
    <html lang="en">

      <body >
      <MyContextProvider>
        <Header />
        {children}
        <Totop/>
        <Footer />
        </MyContextProvider>

      </body>

    </html>
  )
}
export default RootLayout;